import { colors, windowHeight, windowWidth } from "@/utils/Constants/Styles";
import { Platform, StyleSheet } from "react-native";

const cartStyles = StyleSheet.create({
    container: {
        paddingBottom: 0,
        gap: 24,
    },
    headerBar: {
        paddingTop: windowHeight * 0.03,
        height: windowHeight * 0.11,
        backgroundColor: "black",
        borderBottomLeftRadius: 36,
        borderBottomRightRadius: 36,
        paddingHorizontal: 20,
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "space-between",
        zIndex: 20,
    },
    headerBackButton: {
        padding: 2,
        height: 30,
        width: 30,
        zIndex: 20,
        position: "relative",
    },
    headerSpacer: {
        width: 20,
    },
    bannerWrapper: {
        marginTop: Platform.OS === "web" ?  -windowHeight * 0.04 :  -windowHeight * 0.068,
        marginBottom: -windowHeight * 0.04,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 10,
    },
    bannerImage: {
        width: windowWidth * 0.96,
        height: 180,
        resizeMode: "contain",
        alignSelf: "center",
        marginLeft: 24,
        zIndex: 10,
    },
    mainContent: {
        marginTop: 18,
        padding: 20,
    },
    sectionCard: {
        backgroundColor: colors.white,
        borderRadius: 12,
        padding: 20,
        gap: 16,
        marginBottom: 25
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    cartItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 14,
    },
    cartItemInfo: {
        flex: 1,
        gap: 6,
    },
    cartThumb: {
        width: 72,
        height: 72,
        borderRadius: 22,
        overflow: "hidden",
        backgroundColor: colors.gray200,
    },
    cartThumbImage: {
        width: "100%",
        height: "100%",
        resizeMode: "cover",
    },
    cartMetaRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
    },
    favoriteChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        backgroundColor: colors.gray200,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 999,
    },
    quantityBubble: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: colors.gray300,
        backgroundColor: colors.gray200,
    },
    quantityControlRow: {
        alignItems: "center",
        gap: 8,
    },
    quantityButton: {
        width: 20,
        height: 20,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: colors.gray300,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.white,
    },
    cartFooterRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderRadius: 16,
        padding: 12,
        backgroundColor: colors.gray200,
    },
    actionGrid: {
        paddingHorizontal: 20,
        gap: 12,
        flexDirection: "row",
        flexWrap: "wrap",
    },
    actionCard: {
        flexBasis: "48%",
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        padding: 16,
        borderRadius: 24,
        backgroundColor: colors.white,
        borderWidth: 1,
        borderColor: colors.gray200,
    },
    sheetCard: {
        backgroundColor: colors.white,
        borderRadius: 32,
        padding: 20,
        gap: 20,
    },
    orderTypeGrid: {
        flexDirection: "row",
        gap: 12,
    },
    orderTypeCard: {
        flex: 1,
        padding: 16,
        borderRadius: 22,
        borderWidth: 1,
        borderColor: colors.gray300,
        gap: 6,
        backgroundColor: colors.white,
    },
    orderTypeCardActive: {
        backgroundColor: colors.bgGrayCustom,
        borderWidth: 1,
        borderColor: colors.gray300,
    },
    orderTypeIcon: {
        width: 40,
        height: 40,
        borderRadius: 14,
        backgroundColor: colors.white,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: colors.gray300,
    },
    summaryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        gap: 12,
        padding: 8,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.gray300
    },
    summaryPricing: {
        gap: 10,
        borderTopWidth: 1,
        borderTopColor: colors.gray300,
        paddingTop: 12,
    },
    priceRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    priceTotal: {
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: colors.gray300,
        marginTop: 6,
    },
    summaryTotal: {
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: colors.gray300,
        marginTop: 6,
    },
    tagPill: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: colors.bgGrayCustom,
    },
    trackerCard: {
        backgroundColor: colors.white,
        borderRadius: 32,
        padding: 20,
        gap: 16,
    },
    timelineRow: {
        flexDirection: "row",
        gap: 12,
    },
    timelineTime: {
        width: 50,
    },
    timelineMarkerWrap: {
        alignItems: "center",
    },
    timelineMarker: {
        width: 20,
        height: 20,
        borderRadius: 999,
        borderWidth: 2,
        borderColor: colors.gray300,
        backgroundColor: colors.white,
        marginTop: 2,
        justifyContent: "center",
        alignItems: "center",
        padding: 12,
    },
    timelineMarkerActive: {
        borderColor: colors.constrastText,
        backgroundColor: colors.constrastText,
    },
    timelineLine: {
        width: 2,
        flex: 1,
        backgroundColor: colors.gray300,
        marginTop: 2,
    },
    timelineContent: {
        flex: 1,
    },
    supportButton: {
        marginTop: 4,
        backgroundColor: "black",
        borderRadius: 18,
        paddingVertical: 12,
        paddingHorizontal: 18,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    ratingCard: {
        backgroundColor: colors.white,
        borderRadius: 32,
        padding: 20,
        gap: 12,
        alignItems: "center",
    },
    ratingStars: {
        flexDirection: "row",
        gap: 8,
        paddingVertical: 4,
    },
    historyItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.gray300,
    },
    historyInfo: {
        gap: 4,
    },
    historyMeta: {
        alignItems: "flex-end",
        gap: 6,
    },
});

export default cartStyles;
